### PR TITLE
Rename LICENCE.md to LICENSE.md

### PR DESCRIPTION
**Pull request by asheroto**
Description
-----------
Misspelling

Redmine ticket(s)
-----------------

Risk area(s)
------------

### CODE REVIEW

**Comment by mattw-mega** [comment]
licence: noun
license: verb

**Review by stefansulo — COMMENTED** [review]
[](https://mega.nz/C!O15giIwT)

**Comment by stefansulo** [comment]
[](https://mega.nz/C!O15giIwT)

**Comment by asheroto** [comment]
> licence: noun
> license: verb

Ah... in the US we just use "license" for both.

**Pull request closed without merging**
